# Generated by Django 2.0.2 on 2018-02-08 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('login', models.TextField(blank=True, null=True, unique=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('photo', models.FilePathField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('spots', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('location', models.TextField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('photo', models.FilePathField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerapp.Guide')),
            ],
            options={
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='TouristTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerapp.Tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tourist_tour',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='members',
            field=models.ManyToManyField(through='innerapp.TouristTour', to=settings.AUTH_USER_MODEL),
        ),
    ]
