# Generated by Django 2.0.2 on 2018-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
