# Generated by Django 2.0.2 on 2018-02-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innerapp', '0003_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='bio',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='location',
        ),
    ]
