# Generated by Django 2.0.2 on 2018-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerapp', '0004_auto_20180208_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
